# Generated by Django 4.0.5 on 2022-06-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardsapp', '0003_post_url_rating_content_average_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='technologies',
            field=models.TextField(null=True),
        ),
    ]
